# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rihoy   <rihoy@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/11/17 16:31:41 by rihoy             #+#    #+#              #
#    Updated: 2023/11/17 16:31:41 by rihoy            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRCS = ft_printf.c ft_caracteres.c \

OBJS = ${SRCS:.c=.o}

CC = cc
FLAGS = -Wall -Werror -Wextra
NAME = libftprintf_r.a


